dist: trusty
language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install jq
install:
- pip install -e .
- python setup.py install
script:
  - sudo docker-compose up -d
  - make tests
deploy:
  on:
    branch: master
    python: '3.6'
  provider: pypi
  user: valerii.tikhonov
  distributions: bdist_wheel
  password:
    secure: rV988l6VObxqsiiDWScaze+0ArWXcWG5iTzEoZFW0cxU1UzdHwV8y6+ZGFl814nq2GKvW5LrgIFOej0N7nL9+fYsWPlMhbCfVYJSZr8fcQL4sCdJY8QocAa8JcJ+X7x0WwM+442866iXXgn8ulitAK6622Y8E0BRXcRfSQWw0DsWv14LZ/sj/YUJ88dX8tI14wKFlgeDGKGXEneoVAhmPbUk636xTGIIpRue6domM9qIX317EP+D8ndtFirCnIcxBIX4nacbcaxNNvePZKYSrkrfzIZP1itqZrAFZFacTaUFj4t8GEmd2TVmVA3yJM9kEcs7zC2k6ep4uFL3zyDUkGJ+ADXdvIx/rVS/V94dXm1BwZWL46vjmJrXeFkLUm+ieg6nLfmY9Gjg1wwKzSZMhghYTxtW8F9r7TVJmc5kasBxgj0DrretXegiknKa8RtzW8lMMrWja0k/I9028Oq0BJybTMP/uR73wVMI1WQgGoxoNDqCHEUzfJUKyxKSNz3ZKq59US03ptKPSXJ4RGDsOxU52APVipFlHkjG0gACbznpewu9DBZpR1N+H0sPZskgcN+xeknn7tQrYo2PBbt4sHsS1Twls6UbEzO9uaq+W58zmH9c9FVYItEfwD7TxXBqXNgSxdNKKgj+zfP27vKHDLurXYn29rA5Qak6tCm/XqY=
