version: '3.1'

services:
  postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=test
        - POSTGRES_USER=test
        - POSTGRES_DB=test
      ports:
        - "5433:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data