version: '3.1'

services:
  postgres:
      image: "postgres"
      environment:
        - POSTGRES_PASSWORD=test
        - POSTGRES_USER=test
        - POSTGRES_DB=test
      ports:
        - "5433:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

  redis:
      image: redis
      ports:
        - "6379:6379"
  kafka:
      image: "spotify/kafka"
      ports:
        - "2181:2181"
        - "9092:9092"
      environment:
        - ADVERTISED_HOST=localhost
        - ADVERTISED_PORT=9092
