version: '3.1'

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    ports:
    - "5433:5432"

  redis:
    image: redis
    ports:
    - "6379:6379"

  kafka:
    image: "spotify/kafka"
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
      ADVERTISED_HOST: "localhost"
      ADVERTISED_PORT: "9092"

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "test"

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
    - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test1234"

  mysql:
    image: mysql
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"

