name: Docker

on:
  push:
    branches: [ master ]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      # Get tag from python code
      - name: Get current version
        run: echo "::set-output name=TAG::$(cat catcher_modules/__init__.py | grep -oP '(\d+\.)(\d+\.)(\*|\d+)')"
        id: get-tag

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            comtihon/catcher:latest
            comtihon/catcher:${{ steps.get-tag.outputs.TAG }}
            ghcr.io/comtihon/catcher:latest
            ghcr.io/comtihon/catcher:${{ steps.get-tag.outputs.TAG }}
